def convert_rbf_to_header(rbf_filename, header_filename, array_name):
    with open(rbf_filename, 'rb') as rbf_file:
        rbf_data = rbf_file.read()

    with open(header_filename, 'w') as header_file:
        header_file.write(f"// Autogenerated from {rbf_filename}\n")
        header_file.write(f"const unsigned char {array_name}[] = {{\n")

        for i, byte in enumerate(rbf_data):
            header_file.write(f"0x{byte:02x}, ")
            if (i + 1) % 12 == 0:  # 12 bytes per line
                header_file.write("\n")

        header_file.write("\n};\n")
        header_file.write(f"const unsigned int {array_name}_size = {len(rbf_data)};\n")