"""
File: rbf_to_header_converter.py

Overview:
    This script converts an RBF (Raw Binary File) to a C/C++ header file that contains the binary data as a
    const unsigned char array. It includes error checking for file existence and handles exceptions during file
    operations to ensure reliability. The generated header file includes the size of the array for convenience.

Features:
    - Command-line argument parsing with `argparse`.
    - Checks if the RBF file exists before processing.
    - Reads binary data from the RBF file and writes it to a specified header file in hexadecimal format.gdb
    - Supports specifying the output header file name and array name, with defaults provided.

Usage:
    python rbf_to_header_converter.py <rbf_filename> [--header_filename <header_filename>] [--array_name <array_name>]

    Examples:
        python rbf_to_header_converter.py QS1R_MASTER_RXTX.rbf
        python rbf_to_header_converter.py QS1R_MASTER_RXTX.rbf --header_filename custom_header.hpp --array_name custom_array

Notes:
    - Default values: header_filename = "qs_bitstream.hpp", array_name = "fpga_bitstream".
    - The script will print an error message if the RBF file does not exist or if any I/O operations fail.

Author: Philip A Covington
Date: 2024-10-28
"""

import os
import argparse

def convert_rbf_to_header(rbf_filename, header_filename='qs_bitstream.hpp', array_name='fpga_bitstream'):
    # Check if the RBF file exists
    if not os.path.isfile(rbf_filename):
        print(f"Error: The file '{rbf_filename}' does not exist.")
        return

    try:
        # Attempt to open the RBF file for reading
        with open(rbf_filename, 'rb') as rbf_file:
            rbf_data = rbf_file.read()
    except IOError as e:
        print(f"Error reading the RBF file '{rbf_filename}': {e}")
        return

    try:
        # Attempt to open the header file for writing
        with open(header_filename, 'w') as header_file:
            header_file.write(f"// Autogenerated from {rbf_filename}\n")
            header_file.write(f"const unsigned char {array_name}[] = {{\n")

            for i, byte in enumerate(rbf_data):
                header_file.write(f"0x{byte:02x}, ")
                if (i + 1) % 12 == 0:  # 12 bytes per line
                    header_file.write("\n")

            header_file.write("\n};\n")
            header_file.write(f"const unsigned int {array_name}_size = {len(rbf_data)};\n")

        print(f"Header file '{header_filename}' generated successfully.")
    except IOError as e:
        print(f"Error writing to the header file '{header_filename}': {e}")

def main():
    parser = argparse.ArgumentParser(description="Convert an RBF file to a C header file.")
    parser.add_argument("rbf_filename", help="The input RBF file path")
    parser.add_argument("--header_filename", default="qs_bitstream.hpp", help="The output header file path (default: qs_bitstream.hpp)")
    parser.add_argument("--array_name", default="fpga_bitstream", help="The name of the array in the header file (default: fpga_bitstream)")
    
    args = parser.parse_args()
    convert_rbf_to_header(args.rbf_filename, args.header_filename, args.array_name)

if __name__ == "__main__":
    main()
